### ISSUE TITLE
Strange error

### ISSUE THREAD

**Issue by MFernflower** [spadavec/OSM-ML-#1]
![7676](https://cloud.githubusercontent.com/assets/3164942/23089348/7e36711a-f555-11e6-9d04-94b1302405b5.png)

**Comment by spadavec** [comment]
@MFernflower I apparently errounously deleted a random character in the rxn-smarts-filtered.txt file--my apologies. I fixed the error to the file and re-uploaded it, and it now has a new link: 

https://drive.google.com/open?id=0BwZfr-C9jYBIWnJsWjJiVlpPREE

Try running the calculation again with this file and it should work! Sorry for that.

**Comment by MFernflower** [comment]
Thank you!

**Comment by MFernflower** [comment]
@spadavec It seems to be working but the live count does not seem to update?? I am using anaconda on windows 
![image](https://cloud.githubusercontent.com/assets/3164942/23089526/05a80eae-f558-11e6-9d44-d96b88aef989.png)

**Comment by spadavec** [comment]
@MFernflower That might be an oddity with the way the windows environment handles print carriage returns; can you check if a python process is running via command explorer? So long as the process doesn't exit out, it should be running. If you're only running 1 compound, I think that should be done in ~1hour. 

Thanks for bringing this up though, will investigate

**Comment by MFernflower** [comment]
Thank you

**Comment by MFernflower** [comment]
@spadavec Btw, did you get those predicted potencies?

**Comment by spadavec** [comment]
@MFernflower Just posted to OSM; did your calculation finish?

**Comment by MFernflower** [comment]
@spadavec MMP was aborted because of ram usage. I'm really more interested in the prediction simulator but tensorflow does not seem to want to work on my current setup.. Do you think any of my compounds are worth the team making?

**Comment by MFernflower** [comment]
@spadavec The only system I have running linux is a raspberry pi v3. Do you think the potency simulation will run on it?

**Comment by spadavec** [comment]
Hm, I doubt it--because of the size of the libraries involved, its quite memory hungry (as you've noticed). Let me see if I can reduce the memory overhead and make it more viable for you. Do you know how much memory is on your windows machine?

**Comment by MFernflower** [comment]
I can allocate up to seven gigabytes to python. No more no less

**Comment by MFernflower** [comment]
@spadavec I can allocate up to seven gigabytes to python

**Comment by spadavec** [comment]
@MFernflower Looks like we're in luck! I was able to get the footprint down to <1GB memory usage. Just updated the repo, so pull it again and have another shot at it. I also changed it so that it prints the reaction number more often. Sorry for all the back and forth, but this should work quite well for you.

**Comment by MFernflower** [comment]
@spadavec now all we need to do is give it a name! trophozoite has a nice
ring to it!

**Comment by MFernflower** [comment]
@spadavec I think its working!!!!!
![workinggreat](https://cloud.githubusercontent.com/assets/3164942/23097688/f87ed34c-f607-11e6-886b-35d0dc62c1be.png)

**Comment by MFernflower** [comment]
@spadavec at 15 million at about the 25 min mark. It's not running as fast as I though but it's only using about 64 mb

**Comment by spadavec** [comment]
@MFernflower good to  hear! There were definitely pockets of time where it slowed down for me on my machine as well, but I believe it still finished in under an hour.

**Comment by MFernflower** [comment]
I am running this under windows... I bet i would get blazing speed if i ran under unbuntu lts with the proper keras cuda driver. Tensorflow does not work with windows anaconda build

**Comment by MFernflower** [comment]
@spadavec MMP generation worked awesome! Tensorflow still refuses to work so no potency modeling atm :-(

**Comment by spadavec** [comment]
Hm, sorry to hear that. What kind of errors are TF/regression.py throwing at you? I'll try installing TF to see if I can replicate this issue, though.

**Comment by MFernflower** [comment]
@spadavec I cannot get the package for tensorflow for windows anaconda if you can link it to me or find one that would begood

**Comment by spadavec** [comment]
@MFernflower ok, I found a way to get everything installed, but its going to require that I upgrade all of the scripts in the repo to python3. I'll get started on that tonight and hopefully will have something in place by tomorrow.

**Comment by MFernflower** [comment]
@spadavec I got my linux system up and running - no need for a rewrite!

**Comment by spadavec** [comment]
@MFernflower Excellent! That saves me a bit of work :) 

If you want to get this up and running on your linux machine, I'd recommend copying the installation you have on your windows machine over, as I'm in the process of fixing the `synthesis.py` script so that it automatically performs searches in an iterative fashion, and the current repo is a bit broken, I think. I should have that fixed within the next few hours (I'm working on it at this moment).

**Comment by spadavec** [comment]
@MFernflower Ok, sorry for the delay but everything should be updated and good to go! Have a look at the README to see my explanation of everything; if something is unclear, just let me know! 

for the tl;dr -- just give `synthesis.py` a few hit SMILES, and it will iteratively generate new ideas that are potent and meet Ro5.     Cheers!
