### ISSUE TITLE
Runtime error

### ISSUE THREAD

**Issue by MFernflower** [spadavec/OSM-ML-#3]
```Total library size: 1 
Running reaction # 41,155,000
Reactions generated 227697 total unique products

Filtering cmpds. for Rule-of-Five...
Traceback (most recent call last):
  File "synthesis.py", line 320, in <module>
    main()
  File "synthesis.py", line 248, in main
    current_num, write_output('enumerated_products.txt', unique_smiles, 'w', 0)
UnboundLocalError: local variable 'current_num' referenced before assignment
root@Mycobox:/home/webcap/Desktop/OSM_mmv_v2#

**Comment by spadavec** [comment]
Fixed that error! Sorry, that was a bad commit by me. 


 I've also tried to take a stab at lowering the RAM usage--in very large datasets I'm seeing some heavy usage (+10GB used). Please let me know if you see this and I'll see what I can do to fix it. In the meantime, I might suggest letting it only run for 1 iteration.

**Comment by MFernflower** [comment]
@spadavec could you push the change to synthesis.py as synthesis2.py ?

**Comment by spadavec** [comment]
@MFernflower I've added support for both a "low" and "high" memory mode. To run "low" memory mode, run the commandline invocation with `--memory low`; this requires ~10-100MB of memory to run. I also added a "high" memory mode, which can be run with `--memory high`; this requires ~11GB of memory, depending on the size of your reaction smarts file.

**Comment by MFernflower** [comment]
Fantastic!
