### ISSUE TITLE
Yet another error??!

### ISSUE THREAD

**Issue by MFernflower** [spadavec/OSM-ML-#4]
```
Reading in hits...

Total library size: 1 
Running reaction # 41,155,000
Reactions generated 227697 total unique products

Filtering cmpds. for Rule-of-Five...

Writing output to enumerated_products.txt...

*******************************************************
*******************************************************
Iteration 1 complete
*******************************************************
Finding MCS matches...
Selecting best candidates for seeds...

Loading pre-existing model...
Traceback (most recent call last):
  File "synthesis.py", line 315, in <module>
    main()
  File "synthesis.py", line 260, in main
    new_seeds = select_best_seeds(child_smiles)
  File "synthesis.py", line 50, in select_best_seeds
    prediction = Regression(arg1, arg2, runtype, smiles)
  File "/home/webcap/Desktop/OSM_mmv_v2/regression.py", line 45, in __init__
    self.create_model()
  File "/home/webcap/Desktop/OSM_mmv_v2/regression.py", line 101, in create_model
    self.load_model()
  File "/home/webcap/Desktop/OSM_mmv_v2/regression.py", line 93, in load_model
    self.model = load_model(self.model_filename)
  File "/home/webcap/.local/lib/python2.7/site-packages/keras/models.py", line 135, in load_model
    f = h5py.File(filepath, mode='r')
  File "/home/webcap/.local/lib/python2.7/site-packages/h5py/_hl/files.py", line 272, in __init__
    fid = make_fid(name, mode, userblock_size, fapl, swmr=swmr)
  File "/home/webcap/.local/lib/python2.7/site-packages/h5py/_hl/files.py", line 92, in make_fid
    fid = h5f.open(name, flags, fapl=fapl)
  File "h5py/_objects.pyx", line 54, in h5py._objects.with_phil.wrapper (/tmp/pip-4rPeHA-build/h5py/_objects.c:2684)
  File "h5py/_objects.pyx", line 55, in h5py._objects.with_phil.wrapper (/tmp/pip-4rPeHA-build/h5py/_objects.c:2642)
  File "h5py/h5f.pyx", line 76, in h5py.h5f.open (/tmp/pip-4rPeHA-build/h5py/h5f.c:1930)
IOError: Unable to open file (Unable to open file: name = 'sequential_model.h5', errno = 2, error message = 'no such file or directory', flags = 0, o_flags = 0)
webcap@Mycobox:~/Desktop/OSM_mmv_v2$

**Comment by spadavec** [comment]
Is your installation up to date? There should be a `sequential_model.h5` file in there which is used to run the potency prediction.

**Comment by MFernflower** [comment]
@spadavec I will reinstall software tomorrow - My intel core i5 nuc i use to do computations is on cool down now..

**Comment by MFernflower** [comment]
A error occurred when i was filtering pains: - need to wair untill tommrow to run another round. this software is brutal!
'''
Reading in hits...

Total library size: 1 
Running reaction # 41,155,000
Reactions generated 227697 total unique products
Total library size: 481 

Traceback (most recent call last):
  File "synthesis.py", line 315, in <module>
    main()
  File "synthesis.py", line 238, in main
    temp_smiles = filter_from_file(product_smiles,filterfile)
  File "synthesis.py", line 82, in filter_from_file
    if x.HasSubstructMatch(z):
Boost.Python.ArgumentError: Python argument types in
    Mol.HasSubstructMatch(Mol, NoneType)
did not match C++ signature:
    HasSubstructMatch(RDKit::ROMol self, RDKit::ROMol query, bool recursionPossible=True, bool useChirality=False, bool useQueryQueryMatches=False)

**Comment by spadavec** [comment]
Can you let me know what your commandline invocation was, and what you were using for input? All of my tests are currently passing.

**Comment by MFernflower** [comment]
I used the pains file included... does it have to be a .csv to work?

**Comment by MFernflower** [comment]
@spadavec Here is an exact capture of the console:
'''
webcap@Mycobox:~$ cd '/home/webcap/Desktop/OSM-ML--master' 
webcap@Mycobox:~/Desktop/OSM-ML--master$ ls
all-osm-data.csv  modelA.csv  README.md      sequential_model.h5
input.csv         modelB.csv  regression.py  synthesis.py
LICENSE           pains.txt   rxn.csv
webcap@Mycobox:~/Desktop/OSM-ML--master$ python synthesis.py --hits input.csv --filter pains.txt --reactions rxn.csv 
Using TensorFlow backend.
*******************************************************
*******************************************************

Starting MMP driven sythesis...

*******************************************************
*******************************************************
Reading in hits...

Total library size: 1 
Running reaction # 41,155,000
Reactions generated 227697 total unique products
Total library size: 481 
Traceback (most recent call last):
  File "synthesis.py", line 315, in <module>
    main()
  File "synthesis.py", line 238, in main
    temp_smiles = filter_from_file(product_smiles,filterfile)
  File "synthesis.py", line 82, in filter_from_file
    if x.HasSubstructMatch(z):
Boost.Python.ArgumentError: Python argument types in
    Mol.HasSubstructMatch(Mol, NoneType)
did not match C++ signature:
    HasSubstructMatch(RDKit::ROMol self, RDKit::ROMol query, bool recursionPossible=True, bool useChirality=False, bool useQueryQueryMatches=False)
webcap@Mycobox:~/Desktop/OSM-ML--master$

**Comment by MFernflower** [comment]
I am also having an issue with potency prediction:

```
webcap@Mycobox:~/Desktop/OSM-ML--master$ python regression.py --input_file potency_input.csv --model_file modelB.csv 
Using TensorFlow backend.

Loading data...
Traceback (most recent call last):
  File "regression.py", line 210, in <module>
    main()
  File "regression.py", line 204, in main
    testing_data, training_data = split_types(data)
  File "regression.py", line 168, in split_types
    if x[2] in train_sets:
IndexError: list index out of range
webcap@Mycobox:~/Desktop/OSM-ML--master$ ls
enumerated_products.txt  modelB.csv         regression.pyc       synthesis.py
hitfile.csv              potency_input.csv  rxn.csv
modelA.csv               regression.py      sequential_model.h5
webcap@Mycobox:~/Desktop/OSM-ML--master$

**Comment by spadavec** [comment]
@MFernflower I'm currently running a debug version with your input on `synthesis.py`, and will report back when if/when I see the same error. 

As for `regression.py`, the nomenclature is a bit confusing, and I updated the README to reflect that. All that is needed to run the regression is: 

```python regression.py --input_file modelB.csv```

The "model file" I mentioned is actually the `sequential_model.h5` file in your directory. The script will automatically use that, so theres no need to specify it. All of the predictions will be printed on screen and put into `regression-predictions.txt`. All you need to do is copy/paste relevant lines from your `enumerated_products.txt` file into `modelB.csv` and those will be used as predictions.

**Comment by MFernflower** [comment]
@spadavec How should my smiles be added to modelB.csv?

**Comment by spadavec** [comment]
For adding new data to `modelB.csv', the formatting is a csv, with the following columns: 

`integer`, `integer`, `B`, `smiles_string`,`unique_id`

e.g. 

`10,2,B,CC1(C)CCN(CCOC2=CN=CC3=NN=C(N23)C2=CC=C(OC(F)F)C=C2)CC1,END-F37GC5`

The actual values of the first two integers dont matter; just make sure 'B' is in the third column, smiles in the 4th, and ID in the 5th. All of the text in `enumerated_products.txt` is formatted correctly for you :)

**Comment by MFernflower** [comment]
@spadavec Thanks for being so helpful! This is the result of my test run: MFC-001,N#CC=1C=CC(=CC=1)C4=NN=C3C=NC=C(OCC(O)COCC=2C=CC(F)=CC=2)N34,0.219472438097 

LogP is gonna be high but this seems like a good lead

**Comment by spadavec** [comment]
Excellent! Just so you know, when I was working on this for the competition, the accuracy was roughly ~0.65, meaning that two smiles need a pEC50 of at least 0.65 difference to comfortably say one is more potent than the other. The most potent compounds in the competition had pEC50 values of about -0.6, so your compound is very likely to be less potent (10^0.21 ~= 2  microM), but it looks interesting!

**Comment by MFernflower** [comment]
@spadavec I see. I will post onto edwins thread about making compounds generated from this software

**Comment by spadavec** [comment]
@MFernflower I just ran `synthesis.py` using your input smiles and didn't see any errors. I've attached the output here for your reference: 

[enumerated_products.zip](https://github.com/spadavec/OSM-ML-/files/800262/enumerated_products.zip)

I'm guessing that your `pains.txt` got corrupted somehow? The pains file in the repo now should be fine, so I'd suggest getting your installation up-to-date (if it isn't already) and try again?

**Comment by MFernflower** [comment]
Thank you

**Comment by MFernflower** [comment]
@spadavec Latest test results.. Could you make this program spit out the predicted micromolar value? 

OC(COCC1=CC=CC=C1)COC1=CN=CC2=NN=C(N12)C1=CC=C(OC(F)F)C=C1,-0.0199673436582

**Comment by spadavec** [comment]
@MFernflower sure thing; All thats needed to be done in the mean time is to do 10^pEC50; in this case 10^-0.02 so ~1 microM.

**Comment by MFernflower** [comment]
This seems like a nice mol to try. Could you post over to osm gh? Im busy
today

**Comment by MFernflower** [comment]
@spadavec Please add this feature when you have spare time. Thank you

**Comment by spadavec** [comment]
@MFernflower Just added this; EC50 values are reported to both output csv file and terminal--sorry for the delay (been busy starting a company :) ). Also, if your Linux machine has at least 11GB memory, I can push a change that makes `synthesis.py` run ~8x faster.

**Comment by MFernflower** [comment]
Just place an order in for another eight gigabytes will be here in a week

**Comment by spadavec** [comment]
Awesome! I'll wait to push that change then. Cheers.

**Comment by MFernflower** [comment]
@spadavec You could always provide a diffrent file with the updated code
