### ISSUE TITLE
Output csv does not contain compound SMILES (see screencap)

### ISSUE THREAD

**Issue by MFernflower** [spadavec/OSM-ML-#5]
![screenshot at 2017-03-07 14 59 39](https://cloud.githubusercontent.com/assets/3164942/23675248/c625aa1e-0346-11e7-9fe7-534c9e8bc7b7.png)

**Comment by spadavec** [comment]
@MFernflower sorry, I had a faulty unit test that didn't catch this. I just pushed a fix and everything should be working now.

**Comment by MFernflower** [comment]
Making this program output the logp's of the input test compounds to that
csv would be really handy! @spadavec
