### ISSUE TITLE
Add automatic logp calcuation for testing molecules?

### ISSUE THREAD

**Issue by MFernflower** [spadavec/OSM-ML-#6]
</div>

**Comment by spadavec** [comment]
Should cLogP be sufficient here? Are there any other pertinent properties that might be relevant here that I could generate (e.g. MW, PSA, etc?). In any case, I should be able to implement this later this afternoon! Thank you for your patience.

**Comment by MFernflower** [comment]
Molecule mass would be nice too. This is  so I can automate screening
without data warrior. I am out hiking at the moment so maybe ask Dr.Todd
what else would be good?

**Comment by spadavec** [comment]
No problem! Please note that I updated the code to use Keras 2.0, so you may need to update your version of Keras if you haven't already.
